### ISSUE TITLE
Initial handshake with master failed component=arangodb error="Post http://x.x.x.x:8528/hello: dial tcp x.x.x.x:8528: connect: no route to host"

### ISSUE THREAD

**Issue by doubleailes** [arangodb/arangodb#10128]
## My Environment

* __ArangoDB Version__: Latest      
* __Storage Engine__: RocksDB            
* __Deployment Mode__: Cluster      
* __Deployment Strategy__: ArangoDB Starter in Docker  
* __Configuration__:               
* __Infrastructure__:  own             
* __Operating System__:   centos 7.4     
* __Total RAM in your machine__:  2Go/2Go/32Go      
* __Disks in use__: HDD       
* __Used Package__:    docker starter          

## Component, Query & Data

__Affected feature__:

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Problem__:
I wanna create a cluster of arrango node with three machines
i used a docker-compose file for each base on the arangodb-starter docker.

Here is my docker-compose file
```
version: "3.3"

services:
  arangodb:
    hostname: arangodb-${REGIONS}
    container_name: arangodb-${REGIONS}
    image: arangodb/arangodb-starter
    environment:
      - ARANGO_NO_AUTH=1
    command:
      --starter.address=${IP}
      --docker.container=arangodb-${REGIONS}
      --starter.join=A,B,192.168.11.62
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "arangodb1:/data"
    ports:
      - "8528:8528"
      - "8529:8529"
volumes:
    arangodb1:
        external: false
```
One of the node refuse to handshake with this error\
```
arangodb-node | 2019-10-01T13:54:57Z |INFO| Contacting master http://x.x.x.x:8528... component=arangodb
arangodb-node | 2019-10-01T13:54:58Z |INFO| Initial handshake with master failed component=arangodb error="Post http://x.x.x.x:8528/hello: dial tcp x.x.x.x:8528: connect: no route to host"
```
__Expected result__:
connection of the cluster
