### ISSUE TITLE
Can't do a full shutdown/restart of 3.5.1 in cluster mode

### ISSUE THREAD

**Issue by scanon** [arangodb/arangodb#10343]
## My Environment

* __ArangoDB Version__:        3.5.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:  Manual Start in Docker
* __Configuration__:               3 node VM cluster
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        64 GB
* __Disks in use__:        HDD
* __Used Package__:              Docker

## Component, Query & Data

__Affected feature__:
Cluster DBserver

__AQL query (if applicable)__:
N/A

__AQL explain (if applicable)__:
N/A

__Dataset__:
Empty/Doesn't matter

__Size of your Dataset on disk__:
N/A

__Replication Factor & Number of Shards (Cluster only)__:
1/1

## Steps to reproduce

1. Initialize a cluster
2. Do a full shutdown
3. Try to restart

__Problem__:
We are unable to restart an Arango 3.5 cluster after a full shutdown.  It appears that the shard with the system info gets in some deadlock.  The only clear error is on the DB servers during restart.  All will complain with...

```01 2019-10-30T07:45:13.950518801Z 2019-10-30T07:45:13Z [1] INFO [b6826] {cluster} Cluster feature is turned on. Agency version: {"server":"arango","license":"community","version":"3.5.0"}, Agency endpoints: http+tcp://agency1:8530, server id: 'PRMR-926d454b-d896-4612-b555-d751cf31ee6a', internal endpoint / address: tcp://db1:8530', advertised endpoint: , role: PRIMARY

01 2019-10-30T07:45:13.950548954Z 2019-10-30T07:45:13Z [1] INFO [805b2] {cluster} using heartbeat interval value '1000 ms' from agency

01 2019-10-30T07:45:13.964303497Z 2019-10-30T07:45:13Z [1] INFO [b82cb] {cluster} cannot create connection to server: 'PRMR-ee8f3bab-d02d-47ca-85d4-634ed50f66bd' at endpoint 'tcp://db3:8530', timeout: 2.000000

01 2019-10-30T07:45:13.964334754Z 2019-10-30T07:45:13Z [1] ERROR [8f0bc] {cluster} ClusterComm::performRequests: got no answer from shard:s3010020:/_db/_system/_api/simple/all?collection=s3010020 with status backend unavailable

01 2019-10-30T07:45:14.042235104Z 2019-10-30T07:45:14Z [1] ERROR [4ec19] {startup} startup aborted: caught exception during start of feature 'ArangoSearchAnalyzer': could not connect to server. shutting down

```

Note you will see this error even on the DB node that is associated with the shard.  So it is as if the DB server or maybe its the agency server is trying to connect to the database that is being started up, and it isn't ready yet.

This is seriously impacting our ability to continue using 3.5.

I can paste our compose file so you can see the options.

__Expected result__:
Can restart without issues or special measures

**Comment by scanon** [comment]
Here is the compose   This is for a Rancher cluster but I don't think that is too relevant here.

```yaml
version: '2'
services:
  db1:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/db1:/var/lib/arangodb3
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://db1:8530
    - --cluster.my-role
    - PRIMARY
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=1

  agency1:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/agency1:/var/lib/arangodb3
    tty: true
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --agency.activate
    - 'true'
    - --agency.size
    - '1'
    - --agency.supervision
    - 'true'
    - --agency.my-address
    - tcp://agency1:8530
    - --server.endpoint
    - tcp://0.0.0.0:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=1

  db3:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/db3:/var/lib/arangodb3
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://db3:8530
    - --cluster.my-role
    - PRIMARY
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=3

  coordinator1:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/coordinator1:/var/lib/arangodb3
    tty: true
    ports:
    - 8530:8530/tcp
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://coordinator1:8530
    - --cluster.my-role
    - COORDINATOR
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=1
  db2:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/db2:/var/lib/arangodb3
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://db2:8530
    - --cluster.my-role
    - PRIMARY
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=2
  coordinator2:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/coordinator2:/var/lib/arangodb3
    ports:
    - 8530:8530/tcp
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://coordinator2:8530
    - --cluster.my-role
    - COORDINATOR
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=2
  coordinator3:
    image: arangodb:3.5
    environment:
      ARANGO_ROOT_PASSWORD_FILE: /var/run/secrets/arango-pass
    volumes:
    - /data/arango3.5/coordinator3:/var/lib/arangodb3
    ports:
    - 8530:8530/tcp
    secrets:
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango_3_5-jwt
      target: arango-jwt
    - mode: '0400'
      uid: '0'
      gid: '0'
      source: arango-pass
      target: arango-pass
    command:
    - arangod
    - --server.jwt-secret-keyfile=/var/run/secrets/arango-jwt
    - --server.endpoint
    - tcp://0.0.0.0:8530
    - --cluster.my-address
    - tcp://coordinator3:8530
    - --cluster.my-role
    - COORDINATOR
    - --cluster.agency-endpoint
    - tcp://agency1:8530
    labels:
      io.rancher.scheduler.affinity:host_label: us.kbase.graphnode=3
secrets:
  arango_3_5-jwt:
    external: 'true'
  arango-pass:
    external: 'true'

```
