### ISSUE TITLE
Shards rebalancing is not possible, why?

### ISSUE THREAD

**Issue by effesessa** [arangodb/arangodb#12123]
## My Environment

* __ArangoDB Version__:        3.6.2
* __Storage Engine__:             RocksDB 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Configuration__:              
```yaml
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "cluster"
spec:
  externalAccess:
    type: NodePort
  auth:
    jwtSecretName: None
  tls:
    caSecretName: None
  mode: Cluster
  image: arangodb/arangodb:3.6.2
```

* __Infrastructure__:               Azure
* __Total RAM in your machine__:  16GB for every node
* __Disks in use__:                 azure disks SSD 8GB for every dbserver
* __Used Package__:              Docker - official Docker library

note: 3 dbservers, 3 coordinators and 3 agents are used

__Replication Factor & Number of Shards (Cluster only)__:
3 shards for every collection
3 replication factor for every collection

__Problem__:
when i scale the dbservers i would like to rebalance the shards. I scale through web UI, but I can only do this if I select the _system database. ok this does not matter and does not create any problem! 
But when I have to carry out the rebalancing of the shards I have to necessarily select the db of interest. The problem is that selecting another db other than _system the button is not displayed to perform the operation.

Hoping for a solution, I would like to know if it is possible to rebalance through arangosh or another client tool

Thanks
