### ISSUE TITLE
how to pass rocksdb configurations using k8s (ArangoDeployment?) ?

### ISSUE THREAD

**Issue by effesessa** [arangodb/arangodb#12302]
Hello everyone,

how to pass these configuration https://www.arangodb.com/docs/stable/programs-arangod-rocksdb.html using k8s?

**Comment by ajanikow** [comment]
Hello!

You can pass additional command line arguments thru args section in ArangoDeployment: https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupargs-string

Best Regards,
Adam Janikowski.

**Comment by effesessa** [comment]
ok, thanks!

I have this arangodeployment! is it right?????



```yaml
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "cluster"
spec:
  externalAccess:
    type: NodePort
  auth:
    jwtSecretName: None
  tls:
    caSecretName: None
  mode: Cluster
  image: arangodb/arangodb:3.6.2
  dbservers:
    count: 3
  coordinators:
    count: 3
  rocksdb:
    write-buffer-size: 1024MiB
    total-write-buffer-size: 6
```

Using kubectl describe for dbservers, the option is not specified about rocksdb.

ouput
```
Name:         cluster-prmr-xub6gkmc-12ce1e
Namespace:    arango
Priority:     0
Node:         aks-nodepool1-29663928-vmss000001/10.240.0.5
Start Time:   Mon, 27 Jul 2020 16:45:49 +0200
Labels:       app=arangodb
              arango_deployment=cluster
              role=dbserver
Annotations:  <none>
Status:       Running
IP:           10.244.3.23
IPs:
  IP:           10.244.3.23
Controlled By:  ArangoDeployment/cluster
Init Containers:
  init-lifecycle:
    Container ID:  docker://f09e6cddfa603667ae6a2a3b07203d9a482ac9ae46b76d672643afbe9e82d50d
    Image:         arangodb/kube-arangodb:1.0.1
    Image ID:      docker-pullable://arangodb/kube-arangodb@sha256:4e2cb64bfb8d1089b17c5f89c4770e00c631f7423aba49677ea199a6e8e46f7d
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/arangodb_operator
      lifecycle
      copy
      --target
      /lifecycle/tools
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 27 Jul 2020 16:48:08 +0200
      Finished:     Mon, 27 Jul 2020 16:48:08 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /lifecycle/tools from lifecycle (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w85r6 (ro)
  uuid:
    Container ID:  docker://a7c6e7007c810565b41a6b8b4d573463df2c18ebe2d74a1a3dd1d3b211ea2da6
    Image:         alpine:3.11
    Image ID:      docker-pullable://alpine@sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      test -f /data/UUID || echo 'PRMR-xub6gkmc' > /data/UUID
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 27 Jul 2020 16:48:10 +0200
      Finished:     Mon, 27 Jul 2020 16:48:10 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        100m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /data from arangod-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w85r6 (ro)
Containers:
  server:
    Container ID:  docker://8b180e6dfab4dd12d776aedd3e4e6f7c5362ca1a343b31e8379ff21e1c8560af
    Image:         arangodb/arangodb@sha256:cf9f41636d1022425f0d2e31c2796c808cf3e72436099e0918fe5c284dbdf041
    Image ID:      docker-pullable://arangodb/arangodb@sha256:cf9f41636d1022425f0d2e31c2796c808cf3e72436099e0918fe5c284dbdf041
    Port:          8529/TCP
    Host Port:     0/TCP
    Command:
      /usr/sbin/arangod
      --cluster.agency-endpoint=tcp://cluster-agent-hiffwuz9.cluster-int.arango.svc:8529
      --cluster.agency-endpoint=tcp://cluster-agent-iubzm8j6.cluster-int.arango.svc:8529
      --cluster.agency-endpoint=tcp://cluster-agent-zdhgzdva.cluster-int.arango.svc:8529
      --cluster.my-address=tcp://cluster-dbserver-xub6gkmc.cluster-int.arango.svc:8529
      --cluster.my-role=PRIMARY
      --database.directory=/data
      --foxx.queues=false
      --log.level=INFO
      --log.output=+
      --server.authentication=false
      --server.endpoint=tcp://[::]:8529
      --server.statistics=true
      --server.storage-engine=rocksdb
    State:          Running
      Started:      Mon, 27 Jul 2020 16:48:12 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8529/_api/version delay=900s timeout=2s period=60s #success=1 #failure=10
    Environment:
      MY_POD_NAME:       cluster-prmr-xub6gkmc-12ce1e (v1:metadata.name)
      MY_POD_NAMESPACE:  arango (v1:metadata.namespace)
      MY_NODE_NAME:       (v1:spec.nodeName)
      NODE_NAME:          (v1:spec.nodeName)
    Mounts:
      /data from arangod-data (rw)
      /lifecycle/tools from lifecycle (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-w85r6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  arangod-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  cluster-dbserver-xub6gkmc
    ReadOnly:   false
  lifecycle:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-w85r6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-w85r6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/unreachable:NoExecute for 300s
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age   From                                        Message
  ----     ------                  ----  ----                                        -------
  Normal   Scheduled               44m   default-scheduler                           Successfully assigned arango/cluster-prmr-xub6gkmc-12ce1e to aks-nodepool1-29663928-vmss000001
  Normal   SuccessfulAttachVolume  42m   attachdetach-controller                     AttachVolume.Attach succeeded for volume "pvc-cf5295dc-90cf-4194-97ac-4696e1a244a8"
  Warning  FailedMount             42m   kubelet, aks-nodepool1-29663928-vmss000001  Unable to attach or mount volumes: unmounted volumes=[arangod-data], unattached volumes=[arangod-data lifecycle default-token-w85r6]: timed out waiting for the condition
  Normal   Pulled                  42m   kubelet, aks-nodepool1-29663928-vmss000001  Container image "arangodb/kube-arangodb:1.0.1" already present on machine
  Normal   Created                 42m   kubelet, aks-nodepool1-29663928-vmss000001  Created container init-lifecycle
  Normal   Started                 42m   kubelet, aks-nodepool1-29663928-vmss000001  Started container init-lifecycle
  Normal   Pulled                  42m   kubelet, aks-nodepool1-29663928-vmss000001  Container image "alpine:3.11" already present on machine
  Normal   Created                 42m   kubelet, aks-nodepool1-29663928-vmss000001  Created container uuid
  Normal   Started                 42m   kubelet, aks-nodepool1-29663928-vmss000001  Started container uuid
  Normal   Pulled                  41m   kubelet, aks-nodepool1-29663928-vmss000001  Container image "arangodb/arangodb@sha256:cf9f41636d1022425f0d2e31c2796c808cf3e72436099e0918fe5c284dbdf041" already present on machine
  Normal   Created                 41m   kubelet, aks-nodepool1-29663928-vmss000001  Created container server
  Normal   Started                 41m   kubelet, aks-nodepool1-29663928-vmss000001  Started container server
```

**Comment by effesessa** [comment]
ok i think i didn't understand.
```yaml
spec:
  dbserver:
    args: ["--rocksdb.write-buffer-size 1024MiB", "--rocksdb.max-write-buffer-number 6"]
```
Is it right?

Thanks

**Comment by ajanikow** [comment]
Hello!

You can use it like in example:

```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "example-arangodb-cluster"
spec:
  mode: Cluster
  environment: Production
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: ssd
  dbservers:
    args:
       - "--rocksdb.write-buffer-size=1024MiB"
       - "--rocksdb.max-write-buffer-number=6"
    count: 5
    resources:
      requests:
        storage: 80Gi
    storageClassName: ssd
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.3.4"
```
