### ISSUE TITLE
[cluster setup]The first setup 3 agency is failed. 

### ISSUE THREAD

**Issue by yangchao0512** [arangodb/arangodb#12533]
## My Environment

 __ArangoDB Version__:        3.6.3
 __Storage Engine__:             RocksDB 
 __Deployment Mode__:      Cluster 
 __Deployment Strategy__:   Manual Start 
 __Configuration__:               cluster setup details
 __Infrastructure__:               own 
 __Operating System__:        centos7
 __Total RAM in your machine__:        64GiB for 6 machines
 __Disks in use__:                HDD
 __Used Package__:             RedHat .rpm

## Component, Query & Data

__Affected feature__:

The cluster can‘t use anymore

__AQL query (if applicable)__:

__AQL explain (if applicable)__:

__Dataset__:

__Size of your Dataset on disk__:
50GB

__Replication Factor & Number of Shards (Cluster only)__:

Replication Factor 3
Number of Shards 3

## Steps to reproduce
agency node：
56.18.30.240
56.18.30.241
56.18.30.242
dbserver node and coordinator node：
56.18.30.243
56.18.30.244
56.18.30.245
1. 56.18.30.240
arangod --server.endpoint tcp://0.0.0.0:8531 \
  --agency.my-address tcp://56.18.30.240:8531 \
  --server.authentication false \
  --agency.activate true \
  --agency.size 3 \
  --agency.endpoint tcp://56.18.30.241:8531 \
  --agency.endpoint tcp://56.18.30.242:8531 \
  --agency.supervision true \
  --database.directory /var/lib/arangodb3/agency8531/data

2. 56.18.30.241  
arangod --server.endpoint tcp://0.0.0.0:8531 \
  --agency.my-address tcp://56.18.30.241:8531 \
  --server.authentication false \
  --agency.activate true \
  --agency.size 3 \
  --agency.endpoint tcp://56.18.30.240:8531 \
  --agency.endpoint tcp://56.18.30.242:8531 \
  --agency.supervision true \
  --database.directory /var/lib/arangodb3/agency8531/data

3. 56.18.30.242
arangod --server.endpoint tcp://0.0.0.0:8531 \
  --agency.my-address tcp://56.18.30.242:8531 \
  --server.authentication false \
  --agency.activate true \
  --agency.size 3 \
  --agency.endpoint tcp://56.18.30.240:8531 \
  --agency.endpoint tcp://56.18.30.241:8531 \ 
  --agency.supervision true \
  --database.directory /var/lib/arangodb3/agency8531/data

__Problem__:
The third node（242） error message：
[root@localhost arangodb3]# arangod --server.endpoint tcp://0.0.0.0:8531 \
>   --agency.my-address tcp://56.18.30.242:8531 \
>   --server.authentication false \
>   --agency.activate true \
>   --agency.size 3 \
>   --agency.endpoint tcp://56.18.30.240:8531 \
>   --agency.endpoint tcp://56.18.30.241:8531 \
>   --agency.supervision true \
>   --database.directory /var/lib/arangodb3/agency8531/data
2020-08-26T01:22:35Z [25679] INFO [e52b0] ArangoDB 3.6.3-1 [linux] 64bit, using jemalloc, build tags/v3.6.3.1-0-g76b2e00b64b-dirty, VPack 0.1.33, RocksDB 6.2.0, ICU 58.1, V8 7.1.302.28, OpenSSL 1.1.1g  21 Apr 2020
2020-08-26T01:22:35Z [25679] INFO [75ddc] detected operating system: Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Mon Jun 30 12:09:22 UTC 2014
2020-08-26T01:22:35Z [25679] INFO [25362] {memory} Available physical memory: 67333894144
2020-08-26T01:22:35Z [25679] WARNING [3e451] {memory} It is recommended to set NUMA to interleaved.
2020-08-26T01:22:35Z [25679] WARNING [b25a4] {memory} put 'numactl --interleave=all' in front of your command
2020-08-26T01:22:35Z [25679] INFO [43396] {authentication} Jwt secret not specified, generating...
2020-08-26T01:22:35Z [25679] INFO [144fe] using storage engine 'rocksdb'
2020-08-26T01:22:35Z [25679] INFO [3bb7d] {cluster} Starting up with role AGENT
2020-08-26T01:22:35Z [25679] INFO [6ea38] using endpoint 'http+tcp://0.0.0.0:8531' for non-encrypted requests
2020-08-26T01:22:35Z [25679] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 8192, soft limit is 8192
2020-08-26T01:22:35Z [25679] INFO [3844e] {authentication} Authentication is turned off, authentication for unix sockets is turned on
2020-08-26T01:22:35Z [25679] INFO [cf3f4] ArangoDB (version 3.6.3-1 [linux]) is ready for business. Have fun!
2020-08-26T01:22:35Z [25679] INFO [7b6f3] {agency} Entering gossip phase ...
2020-08-26T01:22:35Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:36Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:36Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:37Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:39Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:43Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:47Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:51Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:55Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:22:59Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:03Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:07Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:11Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:15Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:19Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:23Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:27Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint
2020-08-26T01:23:31Z [25679] ERROR [bed89] {agency} Got error 500 from gossip endpoint

__Expected result__:
how to fix

**Comment by alp82** [comment]
I have the same problem. The first two nodes connect properly and form a cluster. The third one always shows:

```
ERROR [bed89] {agency} Got error 500 from gossip endpoint
ERROR [bed89] {agency} Got error 500 from gossip endpoint
ERROR [bed89] {agency} Got error 500 from gossip endpoint
```

I can alternate which node I start with and it's always the first second being connected and the third one being rejected via 500. Before each attempt I removed my docker volumes.

Here is the `docker-compose.yml` I use on all three nodes for reference:

```yml
services:
  agent:
    image: arangodb/arangodb:${ARANGO_VERSION}
    container_name: arango_agent
    restart: always
    mem_limit: 1g
    memswap_limit: 1g
    ports:
      - "${SELF_IP}:8531:8531"
    volumes:
      - agent_data:/var/lib/arangodb3
      - ./jwtsecret:/jwtsecret:ro
    environment:
      - ARANGO_NO_AUTH=false
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    command: >
      arangod
      --server.authentication=true
      --server.authentication-system-only=false
      --server.endpoint=tcp://0.0.0.0:8531
      --server.jwt-secret-keyfile=/jwtsecret
      --agency.activate=true
      --agency.my-address=tcp://${SELF_IP}:8531
      --agency.size=3
      --agency.supervision=true
      --agency.endpoint=tcp://${IP_AGENT_1}:8531
      --agency.endpoint=tcp://${IP_AGENT_2}:8531
      --agency.endpoint=tcp://${IP_AGENT_3}:8531
      --database.directory=/var/lib/arangodb3
      --log.level=INFO
      --server.maximal-threads=64
      --tcp.reuse-address=true

  dbserver:
    image: arangodb/arangodb:${ARANGO_VERSION}
    container_name: arango_dbserver
    restart: always
    mem_limit: 18g
    memswap_limit: 18g
    ports:
      - "${SELF_IP}:8530:8530"
    volumes:
      - dbserver_data:/var/lib/arangodb3
      - ./jwtsecret:/jwtsecret:ro
    environment:
      - ARANGO_NO_AUTH=false
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    command: >
      arangod
      --server.authentication=true
      --server.authentication-system-only=false
      --server.endpoint=tcp://0.0.0.0:8530
      --server.jwt-secret-keyfile=/jwtsecret
      --cluster.agency-endpoint=tcp://${IP_AGENT_1}:8531
      --cluster.agency-endpoint=tcp://${IP_AGENT_2}:8531
      --cluster.agency-endpoint=tcp://${IP_AGENT_3}:8531
      --cluster.my-address=tcp://${SELF_IP}:8530
      --cluster.my-role=DBSERVER
      --database.directory=/var/lib/arangodb3
      --log.level=INFO
      --server.maximal-threads=256
      --tcp.reuse-address=true
      --tcp.backlog-size=512
      --server.maximal-queue-size=8192

  coordinator:
    image: arangodb/arangodb:${ARANGO_VERSION}
    container_name: arango_coordinator
    restart: always
    mem_limit: 4g
    memswap_limit: 4g
    ports:
      - "${SELF_IP}:8529:8529"
      #- "8529:8529"
    volumes:
      - ./jwtsecret:/jwtsecret:ro
    environment:
      - ARANGO_NO_AUTH=false
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    command: >
      arangod
      --server.authentication=true
      --server.authentication-system-only=false
      --server.endpoint=tcp://0.0.0.0:8529
      --server.jwt-secret-keyfile=/jwtsecret
      --cluster.agency-endpoint=tcp://${IP_AGENT_1}:8531
      --cluster.agency-endpoint=tcp://${IP_AGENT_2}:8531
      --cluster.agency-endpoint=tcp://${IP_AGENT_3}:8531
      --cluster.my-address=tcp://${SELF_IP}:8529
      --cluster.my-role=COORDINATOR
      --log.level=INFO
      --server.maximal-threads=128
      --tcp.reuse-address=true
      --tcp.backlog-size=256
      --server.maximal-queue-size=8192

volumes:
  agent_data:
  dbserver_data:
```

Arango Version is 3.12.4.3. I checked that the `jwtsecret` is the same on all nodes.
