### ISSUE TITLE
ArangoError 10: can only copy regular files / ArangoError 2: No such file or directory

### ISSUE THREAD

**Issue by riteshapatel** [arangodb/arangodb#13125]
## My Environment

* __ArangoDB Version__:        3.7.3
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   EKS
* __Configuration__:               Single Pod stood up with Arango Operator
* __Infrastructure__:               AWS
* __Operating System__:        Amazon Linux
* __Total RAM in your machine__:        m5.xlarge
* __Disks in use__:        EBS volumes
* __Used Package__:              Amazon Linux
## Component, Query & Data
N/A

__Affected feature__:
Looks like Foxx manager from the error.

__Problem__:

We are seeing these errors on one of the pods running on EKS. We recently upgraded to `3.7.3` and running NodeJs driver against the database. 

![Screen Shot 2020-12-01 at 12 56 39 PM](https://user-images.githubusercontent.com/8109095/100778611-3a0e5300-33d5-11eb-84c7-76b2d1b61686.png)

Does anyone know what could be the reason for this? Where else we should be looking to resolve these errors? 

Thank you

__Expected result__:

**Comment by dothebart** [comment]
yes, could it is distributing the foxx-services to the machines? 
This exception is thrown if: 
```
stbuf.st_mode & S_IFMT) == S_IFREG
```
see https://linux.die.net/man/2/stat for details.

Do you ship symbolic links or similar files via the foxx service bundle?

**Comment by riteshapatel** [comment]
@dothebart thanks for the response. No we do not ship any symbolic links or files via foxx service bundle. What exactly you mean by `distributing foxx-services to the machines`?

**Comment by dothebart** [comment]
if you have several coordinators, they distribute the foxx-services to each other, since they all need to have it.

**Comment by riteshapatel** [comment]
Here is the snapshot of the filesystem. Database files are under `/data`. I am not seeing `_apps` folder anywhere on the data mount. 

**FileSystem**
![Screen Shot 2020-12-02 at 8 59 26 AM](https://user-images.githubusercontent.com/8109095/100883414-4dc1c400-347e-11eb-8b45-523ba8cc9cf0.png)

**Database Files**
![Screen Shot 2020-12-02 at 9 03 59 AM](https://user-images.githubusercontent.com/8109095/100883451-5914ef80-347e-11eb-83f1-3596a8e742ad.png)

Here is the `yaml` that spun up the pod. Nothing super crazy. 

```
metadata:
  name: "dev-arango-instance"
spec:
  mode: Single
  image: arangodb/arangodb:3.7.3
  environment: Development
  externalAccess:
    type: NodePort
    nodePort: {port_number}
  single:
    storageClassName: arangogp2
    resources:
      requests:
        storage: 250Gi
```

`port_number` is the exposed port. 

Where exactly it would put the `_apps` folder? 

Thanks in advance!
