### ISSUE TITLE
Data Is Lost When Redeploying Cluster

### ISSUE THREAD

**Issue by anton-ag** [arangodb/arangodb#13362]
## My Environment

* ArangoDB Version: 3.6.5 (though switching to a newer version is an option)
* Storage Engine: RocksDB
* Deployment Mode: Cluster
* Deployment Strategy:  Manual Start in Docker
* Configuration:  docker-compose stack example is attached below
* Infrastructure: Docker Swarm
* Operating System: 3 CentOS 7 VMs
* Total RAM in your machine: 3 x 16 GB
* Used Package: Docker - official Docker library
* Affected feature: Cluster Installation

Hello! I am currently working on cluster setup for ArangoDB for use in our application. Our environment is Docker Swarm, so what I did was using an image with custom entrypoint. The image is based on an official one, except for having the bind-tools apk package and the said entrypoint added.
What the entrypoint does is discover peers addressing docker built-in dns to discover peers' IPs using `host` utility. Afterwards, ArangoDB is launched using `arangod` with peers' (agents, dbs & coordinators) discovered IPs.
### Problem
The issue I am having right now is losing all the data (all databases) when completely shutting down and re-deploying the stack. 

Current installation uses 3 agents, 2 dbs and 3 coordinators. Compose.yml is as follows:

```
version: '3.8'

services:

  agent:
    image: arango:custom
    environment:
      ARANGO_CLUSTER_ROLE: AGENT
      ARANGO_NO_AUTH: "1"
    networks:
      - pgs-network
    ports:
      - 9002:8529
    entrypoint: /host-entrypoint.sh
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  dbserver:
    image: arango:custom
    environment:
      ARANGO_CLUSTER_ROLE: DBSERVER
      ARANGO_NO_AUTH: "1"
    networks:
      - pgs-network
    volumes:
      - arango_data:/var/lib/arangodb3
    entrypoint: /host-entrypoint.sh
    ports:
      - 9000:8529
    depends_on:
      - agent
    deploy:
      replicas: 2

  coordinator:
    image: arango:custom
    environment:
      ARANGO_CLUSTER_ROLE: COORDINATOR
      ARANGO_NO_AUTH: "1"
    networks:
      - pgs-network
    entrypoint: /host-entrypoint.sh
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    ports:
      - 9001:8529

volumes:
  arango_data:
    driver: local

networks:
  pgs-network:
    external: true
```

Commands used to start processes inside containers:
* Agents:
arangod --server.endpoint tcp://0.0.0.0:8529 --database.directory /var/lib/arangodb3 --server.jwt-secret=#### --agency.activate true --agency.my-address=tcp://10.0.1.127:8529 --agency.supervision true --agency.size 3 --agency.endpoint tcp://10.0.1.128:8529 --agency.endpoint tcp://10.0.1.127:8529 --agency.endpoint tcp://10.0.1.126:8529 --server.authentication=false --config /tmp/arangod.conf
* Coordinators:
arangod --server.endpoint tcp://0.0.0.0:8529 --database.directory /var/lib/arangodb3 --server.jwt-secret=#### --cluster.my-address tcp://10.0.1.133:8529 --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://10.0.1.128:8529 --cluster.agency-endpoint tcp://10.0.1.126:8529 --cluster.agency-endpoint tcp://10.0.1.127:8529 --server.authentication=false --config /tmp/arangod.conf
* Database:
arangod --server.endpoint tcp://0.0.0.0:8529 --database.directory /var/lib/arangodb3 --server.jwt-secret=#### --cluster.my-address tcp://10.0.1.122:8529 --cluster.my-role DBSERVER --cluster.agency-endpoint tcp://10.0.1.128:8529 --cluster.agency-endpoint tcp://10.0.1.126:8529 --cluster.agency-endpoint tcp://10.0.1.127:8529 --server.authentication=false --config /tmp/arangod.conf

Current setup is but a testing variant, so there's no authentication yet. The inner docker IPs are apparently correctly derived on start-up, as clusters launched this way are functional, scalable and failure-resistant to an extent.
What I am yet to figure out is how to redeploy the cluster over existing data. I have not found any bug reports regarding this, so there's got to be something I am not doing right. Thanks in advance!
