### ISSUE TITLE
scale down arangodb deployment for dev environments

### ISSUE THREAD

**Issue by giladsh1** [arangodb/arangodb#17809]
## My Environment

* __ArangoDB Version__:        3.9.2 
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Infrastructure__:               GKE

## deactivating (Scale down) of Arangodb cluster spawned with the operator via a CRD
Hello,  
I am spawning a lot of dev environment with the latest arangodb operator (CRD yaml below).
I was wondering if there is an easy way to scale the cluster at night time / weekend to save cost.
Since the operator creates pod directly, without a managing object such as deployment or statefulset, seems like my only is to update the CRD with count 0 for all components (agent, coordinators, and database servers).
However, when doing so the operator seems stuck and unable to perform this action.
Please advise.

CRD for reference: 
```yaml
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  name: arangodb-cluster
  namespace: infip-test
spec:
  agents:
    count: 3
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    overrideDetectedTotalMemory: true
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
  auth:
    jwtSecretName: None
  coordinators:
    count: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    overrideDetectedTotalMemory: true
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
  dbservers:
    count: 2
    nodeSelector:
      cloud.google.com/gke-nodepool: default-pool
    overrideDetectedTotalMemory: true
    resources:
      limits:
        cpu: 1
        memory: 500Mi
      requests:
        cpu: 1
        memory: 500Mi
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ssd
  disableIPv6: true
  downtimeAllowed: false
  environment: Development
  externalAccess:
    type: None
  image: arangodb/arangodb:3.8.6
  memberPropagationMode: always
  metrics:
    enabled: false
  mode: Cluster
  networkAttachedVolumes: true
  tls:
    caSecretName: None
```
