### ISSUE TITLE
Rocksdb returns compaction issue while trying to import more than 1.2 million records

### ISSUE THREAD

**Issue by Keerthana786** [arangodb/arangodb#18045]
Hello,

I have set up the cluster arango in GKE using the below YAML configuration,

**Environment:**
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "distributed-arango"
  namespace: stage
spec:
  mode: Cluster
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.7'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  image: "arangodb/arangodb:3.7.10"
  environment: Production
  imagePullPolicy: Always
  tls:
    caSecretName: None
  agents:
    count: 3
    args:
      - --log.level=debug
    nodeSelector:
      cloud.google.com/gke-nodepool: stage-node-pool
  dbservers:
    count: 2
    args:
      - --log.level=debug
      - --log.performance=true
      - --log.prefix="ARANGO_LOGS"
      - --query.slow-threshold=40
      - --server.statistics=false
    resources:
      limits:
            cpu: 6000m
            memory: 32Gi
      requests:
        cpu: 6000m
        memory: 32Gi
    volumeClaimTemplate:
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 80Gi
       volumeMode: Filesystem
    storageClassName: premium-rwo
    nodeSelector:
      cloud.google.com/gke-nodepool: stage-node-pool
  coordinators:
    count: 3
    args:
      - --log.level=debug
      - --log.role=true
      - --log.performance=true
      - --log.prefix=ARANGO_LOGS
      - --query.cache-mode="on"
      - --query.slow-threshold=60
      - --cluster.default-replication-factor=2
    resources:
        limits:   
            cpu: 6000m
            memory: 32Gi
        requests:
          cpu: 6000m
          memory: 32Gi
    nodeSelector:
      cloud.google.com/gke-nodepool: stage-node-pool
```

**Problem:**
- I tried to import more than 1.2 million records to the cluster database using the arango-import command  line tool, which throws the following error:
` Error IO error: No space left on the device while appending to file: /data/engine-rocksdb/<file-name>.sst: No space left on device
`
- **Import Command format used:**
`arangoimp --server.endpoint tcp://"host":"port" --server.username "username" --server.password "password" --server.database "dbName" --file "sourceFile" --type json --on-duplicate replace --collection "collection-name"`

**More Context:**
- On checking the disk storage usage,  the used size was not more than ~55GB out of the configured 80GB
- The point at which this error is thrown differs on each run.
- On re-starting the coordinators & db-servers, I was able to load/replace ~120K collections once completely from my local machine as testing, but, on trying to load the same collection from GKE again, the same error was thrown in the arango-logs.
![github](https://user-images.githubusercontent.com/43063410/216962033-a24a3312-da87-4908-936a-b0af0cff0344.png)

What could be the root cause of this compaction issue which is occurring randomly?
