### ISSUE TITLE
Docker Cluster on single server

### ISSUE THREAD

**Issue by elade9977** [arangodb/arangodb#18900]
Hi,

I'm traying to deploy A cluster with docker-compose and arangod.cfg files with 2 agency, 2 coordinator and  3 DB nodes.
I managed to deploy it with 1 agency and without SSL and authentication.

My issue is when I add the second agency the cluster is not working.
What am I missing the the configuration? 
When I'm enable root password I get failed to login any ideas?
Also how can I enable TLS between the whole cluster?

I'm attaching my docker-compose file and example for arangod.cfg

```
version: '3.7'
services:
  agency1: 
    image: arangodb:3.9
    hostname: 'arangodb-agency1'
    container_name: 'arangodb-agency1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['5001:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_agency1.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/agency1:/var/lib/arangodb3
      - /home/ubuntu/docker_arangodb/data_app/agency1:/var/lib/arangodb3-apps
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

  agency2: 
    image: arangodb/arangodb
    hostname: 'arangodb-agency2'
    container_name: 'arangodb-agency2'
    networks:
      - arango_net
    environment:
        - ARANGO_NO_AUTH=1
    ports: ['5002:8529']
    volumes:
       - /home/ubuntu/docker_arangodb/config/arangod_agency2.conf:/etc/arangodb3/arangod.conf
       - /home/ubuntu/docker_arangodb/data/agency2:/var/lib/arangodb3
       - /home/ubuntu/docker_arangodb/data_app/agency2:/var/lib/arangodb3-apps
       - /home/ubuntu/docker_arangodb/certs:/etc/certs

  coordinator:
    image: arangodb:3.9
    hostname: 'arangodb-coordinator1'
    container_name: 'arangodb-coordinator1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['7001:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_coordinator1.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/coordinator:/var/lib/arangodb3
      - /home/ubuntu/docker_arangodb/data_app/coordinator:/var/lib/arangodb3-apps
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

  coordinator2:
    image: arangodb:3.9
    hostname: 'arangodb-coordinator2'
    container_name: 'arangodb-coordinator2'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['7002:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_coordinator2.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/coordinator2:/var/lib/arangodb3
      - /home/ubuntu/docker_arangodb/data_app/coordinator2:/var/lib/arangodb3-apps
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

  db1:
    image: arangodb:3.9
    hostname: 'arangodb-db1'
    container_name: 'arangodb-db1'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['6001:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_db.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/db1:/var/lib/arangodb3'
      - /home/ubuntu/docker_arangodb/data_app/db1:/var/lib/arangodb3-apps'
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

  db2:
    image: arangodb:3.9
    hostname: 'arangodb-db2'
    container_name: 'arangodb-db2'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['6002:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_db2.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/db2:/var/lib/arangodb3
      - /home/ubuntu/docker_arangodb/data_app/db2:/var/lib/arangodb3-apps
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

  db3:
    image: arangodb:3.9
    hostname: 'arangodb-db3'
    container_name: 'arangodb-db3'
    networks:
      - arango_net
    environment:
      - ARANGO_NO_AUTH=1
    ports: ['6003:8529']
    volumes:
      - /home/ubuntu/docker_arangodb/config/arangod_db3.conf:/etc/arangodb3/arangod.conf
      - /home/ubuntu/docker_arangodb/data/db3:/var/lib/arangodb3
      - /home/ubuntu/docker_arangodb/data_app/db3:/var/lib/arangodb3-apps
      - /home/ubuntu/docker_arangodb/certs:/etc/certs

networks:
  arango_net:
    driver: bridge

```

agency1
```
[database]
directory = /var/lib/arangodb3
[server]
endpoint = tcp://0.0.0.0:8529
storage-engine = auto
authentication = false
# gather server statistics
statistics = true
[log]
level = info
file =  -
[agency]
activate = true
my-address = tcp://X.X.X.X:5001
size = 2
endpoint = tcp://X.X.X.X5001
supervision = true
```
agency2
```
[database]
directory = /var/lib/arangodb3
[server]
endpoint = tcp://0.0.0.0:8529
storage-engine = auto
authentication = false
# gather server statistics
statistics = true
[log]
level = info
file =  -
[agency]
activate = true
my-address = tcp://X.X.X.X:5002
size = 2
endpoint = tcp://X.X.X.X5001
supervision = true

```

same cfg for COORDINATOR  just with port 7002
```
[database]
directory = /var/lib/arangodb3
[server]
endpoint = ssl://0.0.0.0:8529
storage-engine = auto
authentication = false
# gather server statistics
statistics = true
[log]
level = info
file =  -
[cluster]
my-address = ssl://X.X.X.X:7001
my-role = COORDINATOR  
agency-endpoint = tcp://X.X.X.X:5001,tcp://X.X.X.X:5002
system-replication-factor = 2
[ssl]
keyfile = /etc/certs/arangodb.pem
```

same cfg for DB just with port 6002,6003
```
[database]
directory = /var/lib/arangodb3
[server]
endpoint = tpc://0.0.0.0:8529
storage-engine = auto
authentication = false
# gather server statistics
statistics = true
[log]
level = info
file =  -
[cluster]
my-address = tcp://X.X.X.X:6001
my-role = DBSERVER 
agency-endpoint = tcp://X.X.X.X:5001,tcp://X.X.X.X:5002

```

Thank you
