### ISSUE TITLE
External Access to Cluster not working on Kubernetes

### ISSUE THREAD

**Issue by giuseppe-martinelli** [arangodb/arangodb#19523]
## My Environment

* __ArangoDB Version__:        3.11.2
* __Deployment Mode__:       Cluster
* __Deployment Strategy__:   Kubernetes
* __Configuration__:              rook/ceph PVC provider 
* __Infrastructure__:               own/kubeadm
* __Operating System__:        Ubuntu 20.04
* __Total RAM in your machine__:        32Gb
* __Disks in use__:        SSD
* __Used Package__:              Docker - official Docker library

## Component, Query & Data

__Affected feature__:
External access

__ArangoDeployment__:
```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  mode: Cluster
  tls:
    caSecretName: None
  #environment: Production
  environment: Development
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: ceph-rbd
  dbservers:
    count: 3
    resources:
      requests:
        storage: 200Gi
    storageClassName: ceph-rbd
  coordinators:
    count: 3
  image: 'arangodb/arangodb:3.11.2'
  externalAccess:
    type: NodePort
    nodePort: 30529

```

__Kubernetes ArangoDeployment__:
```
NAME       AGE
arangodb   92m
```

__Kubernetes Pod__:
```
NAME                                          READY   STATUS      RESTARTS   AGE
arango-deployment-operator-7bc599f7d8-hk7lb   1/1     Running     0          95m
arangodb-agnt-hxn6c9g2-e52e42                 1/1     Running     0          90m
arangodb-agnt-jlrhe1ms-e52e42                 1/1     Running     0          90m
arangodb-agnt-jpbtnzum-e52e42                 1/1     Running     0          90m
arangodb-crdn-bzfcwjqp-e52e42                 1/1     Running     0          90m
arangodb-crdn-fzthnbpw-e52e42                 1/1     Running     0          90m
arangodb-crdn-jgaaj10o-e52e42                 1/1     Running     0          90m
arangodb-prmr-doilpe27-e52e42                 1/1     Running     0          90m
arangodb-prmr-guowgjvb-e52e42                 1/1     Running     0          90m
arangodb-prmr-xhqmvxjt-e52e42                 1/1     Running     0          90m
```

__Kubernetes Persistent Volumes__:
```
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
arangodb-agent-hxn6c9g2      Bound    pvc-df1d1ee2-488c-440a-a2ec-1019a0d12582   8Gi        RWO            ceph-rbd       89m
arangodb-agent-jlrhe1ms      Bound    pvc-c66ed67c-c765-4493-91cd-1222b123df06   8Gi        RWO            ceph-rbd       89m
arangodb-agent-jpbtnzum      Bound    pvc-1a2b4129-4ac5-4886-a53b-575f1c4539cc   8Gi        RWO            ceph-rbd       89m
arangodb-dbserver-doilpe27   Bound    pvc-391a6b54-ec1a-4b65-bf95-7cc40b0f445f   200Gi      RWO            ceph-rbd       89m
arangodb-dbserver-guowgjvb   Bound    pvc-8cc43676-4c6f-4927-af91-96fe94d3771a   200Gi      RWO            ceph-rbd       89m
arangodb-dbserver-xhqmvxjt   Bound    pvc-6085ed89-ebf1-4fd4-83dc-1ff87e241050   200Gi      RWO            ceph-rbd       89m
```

__Kubernetes Services__:
```
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
arango-deployment-operator      ClusterIP   10.105.159.236   <none>        8528/TCP,8628/TCP,8728/TCP   42m
arangodb                        ClusterIP   10.100.60.196    <none>        8529/TCP                     37m
arangodb-agent-hxn6c9g2         ClusterIP   10.99.56.249     <none>        8529/TCP                     37m
arangodb-agent-jlrhe1ms         ClusterIP   10.98.29.65      <none>        8529/TCP                     37m
arangodb-agent-jpbtnzum         ClusterIP   10.98.240.117    <none>        8529/TCP                     37m
arangodb-coordinator-bzfcwjqp   ClusterIP   10.101.228.208   <none>        8529/TCP                     37m
arangodb-coordinator-fzthnbpw   ClusterIP   10.98.145.38     <none>        8529/TCP                     37m
arangodb-coordinator-jgaaj10o   ClusterIP   10.111.55.182    <none>        8529/TCP                     37m
arangodb-dashboard              NodePort    10.101.39.84     <none>        8528:30528/TCP               41m
arangodb-dbserver-doilpe27      ClusterIP   10.106.63.62     <none>        8529/TCP                     37m
arangodb-dbserver-guowgjvb      ClusterIP   10.105.219.146   <none>        8529/TCP                     37m
arangodb-dbserver-xhqmvxjt      ClusterIP   10.102.63.253    <none>        8529/TCP                     37m
arangodb-ea                     NodePort    10.108.108.95    <none>        8529:30529/TCP               37m
arangodb-int                    ClusterIP   None             <none>        8529/TCP                     37m

```

__Operator Dashboard__:
![ArangoDeployment_spec](https://github.com/arangodb/arangodb/assets/25175691/c485c4bf-1491-43b1-83fb-2fc44543feed)

__Problem__:
Despite the ArangoDeployment "arangodb" configuration having the externalAccess parameters set to NodePort, it is not possible to access the cluster from the outside. The dashboard also states that it is not possible, despite the "arangodb-ea" service being created by the operator.

__Expected result__:
Access to the cluster through NodePort
