### ISSUE TITLE
FATAL [c81f6] {general} failed to bind to endpoint 'http+tcp://[::]:8529'. Please check whether another instance is already running using this endpoint and review your endpoints configuration.

### ISSUE THREAD

**Issue by trantuancnt** [arangodb/arangodb#20646]
## Production

* __ArangoDB Version__:        3.11.7
* __Deployment Mode__:       Cluster 
* __Deployment Strategy__:   Kubernetes 
* __Infrastructure__:              own 
* __Operating System__:        Ubuntu 22.04
* __Total RAM in your machine__:        128Gb
* __Disks in use__:        SSD 

## Steps to reproduce

Create deployment with yaml:
```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-cluster"
spec:
  mode: Cluster
  environment: Production
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: arangodb-storage
  dbservers:
    count: 3
    resources:
      requests:
        storage: 80Gi
    storageClassName: arangodb-storage
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.11.7"
```

__Problem__:

Pod created Faild. Check log pod:
`FATAL [c81f6] {general} failed to bind to endpoint 'http+tcp://[::]:8529'. Please check whether another instance is already running using this endpoint and review your endpoints configuration.`

Command pod yaml:
```
command:
        - /usr/sbin/arangod
        - '--database.directory=/data'
        - '--log.output=+'
        - '--server.authentication=false'
        - '--server.endpoint=tcp://[::]:8529'
```
I tried to find a way to change `tcp://[::]:8529` to `tcp://0.0.0.0:8529`  but couldn't fix it
```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-cluster"
spec:
  mode: Cluster
  environment: Production
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: arangodb-storage
  dbservers:
    count: 3
    resources:
      requests:
        storage: 80Gi
    storageClassName: arangodb-storage
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.11.7"
  args:
    - --server.endpoint tcp://0.0.0.0:8529
  sync:
    externalAccess:
      type: "NodePort"
```
__Expected result__:
I want to position configure the endpoint correctly
