### ISSUE TITLE
Suggestion (including quick fix): Make Manuals easier to read and digest

### ISSUE THREAD

**Issue by frankmayer** [arangodb/arangodb#223]
I tested the following css with firebug on several pages inside the manual http://www.arangodb.org/manuals/ and it looks good.

It makes the manuals a lot easier to read and digest.
Just append the following css to http://www.arangodb.org/manuals/include/style.css

``` css
pre.fragment {
    background-color: #FBFCFD;
    border: 1px solid #C4CFE5;
    font-family: monospace,fixed;
    font-size: 105%;
    line-height: 125%;
    margin: 4px 8px 4px 2px;
    overflow: auto;
    padding: 4px 6px;
    word-wrap: break-word;
}
code b {
    background-color: #7E9246;
    border: 1px solid #C4CFE5;
    color: #FFFFFF;
    font-family: monospace,fixed;
    font-size: 105%;
    line-height: 125%;
    margin: 4px 8px 4px 2px;
    overflow: auto;
    padding: 4px 6px;
    word-wrap: break-word;
}
li code {
    background-color: #F0F4E5;
    border: 1px solid #C4CFE5;
    font-family: monospace,fixed;
    font-size: 105%;
    line-height: 250%;
    margin: 4px 8px 4px 2px;
    overflow: auto;
    padding: 4px 6px;
    word-wrap: break-word;
}
p code {
    background-color: #FBFCFD;
    border: 1px solid #C4CFE5;
    font-family: monospace,fixed;
    font-size: 105%;
    line-height: 175%;
    margin: 4px 8px 4px 2px;
    overflow: auto;
    padding: 2px 6px;
    word-wrap: break-word;
}
```
