### ISSUE TITLE
Segfault during init on docker swarm cluster

### ISSUE THREAD

**Issue by crubier** [arangodb/arangodb#3074]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [ ] 2.8
- [ ] 3.0
- [ ] 3.1
- [x] 3.2
- [ ] self-compiled devel branch

Mode:
- [x] Cluster
- [ ] Single-Server

Storage-Engine:
- [x] mmfiles
- [x] rocksdb

On this operating system:
- [ ] DCOS on
  - [ ] AWS
  - [ ] Azure
  - [ ] own infrastructure
- [ ] Linux 
  - [ ] Debian .deb
  - [ ] Ubuntu .deb
  - [ ] SUSE   .rpm
  - [ ] RedHat .rpm
  - [ ] Fedora .rpm
  - [ ] Gentoo
  - [x] docker - official docker library
  - [ ] other:
- [ ] Windows, version: 
- [ ] MacOS, version:

When starting arango in a cluster, I get a segfault on init. Here is the console output:

```
automaticaly choosing storage engine
Initializing root user...Hang on...
/entrypoint.sh: line 141:    10 Segmentation fault      ARANGODB_DEFAULT_ROOT_PASSWORD="$ARANGO_ROOT_PASSWORD" /usr/sbin/arango-init-database
Initializing database...Hang on...
/entrypoint.sh: line 141:    12 Segmentation fault      arangod --server.endpoint unix:///tmp/arangodb-tmp.sock --server.authentication false --log.file /tmp/init-log --log.foreground-tty false
ArangoDB didn't start correctly during init
2017-08-18T13:40:55Z [12] INFO ArangoDB 3.2.1 [linux] 64bit, using jemalloc, VPack 0.1.30, RocksDB 5.6.0, ICU 58.1, V8 5.7.0.0, OpenSSL 1.0.1t  3 May 2016
```

Here is the dockerfile to reproduce this error:

```yml
version: '3'

networks:
  front:
    driver: overlay
  back:
    driver: overlay

services:
  arango-agent-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5001
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-1:5001
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/agent:/var/lib/arangodb3
    networks:
      - back

  arango-agent-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5002
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-2:5002
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/agent:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
    networks:
      - back

  arango-agent-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.endpoint tcp://0.0.0.0:5003
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --agency.my-address=tcp://arango-agent-3:5003
      --agency.size 3
      --agency.endpoint tcp://arango-agent-1:5001
      --agency.supervision true
      --agency.activate true
      --foxx.queues false
      --server.statistics false
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/agent:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
    networks:
      - back

  arango-db-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-1:8529
      --cluster.my-local-info db1
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-db-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-2:8529
      --cluster.my-local-info db2
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-db-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-db-3:8529
      --cluster.my-local-info db3
      --cluster.my-role PRIMARY
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/db:/var/lib/arangodb3
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back

  arango-coord-1:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-1:8529
      --cluster.my-local-info coord1
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango1/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango1/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8001:8529

  arango-coord-2:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-2:8529
      --cluster.my-local-info coord2
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango2/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango2/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8002:8529

  arango-coord-3:
    image: arangodb/arangodb:3.2.1
    deploy:
      mode: replicated
      replicas: 1
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
      ARANGO_AUTHENTICATION: "true"
      ARANGO_JWT_SECRET: ${ARANGO_JWT_SECRET}
    command: arangod
      --server.authentication true
      --server.jwt-secret ${ARANGO_JWT_SECRET}
      --server.endpoint tcp://0.0.0.0:8529
      --cluster.my-address tcp://arango-coord-3:8529
      --cluster.my-local-info coord3
      --cluster.my-role COORDINATOR
      --cluster.agency-endpoint tcp://arango-agent-1:5001
      --cluster.agency-endpoint tcp://arango-agent-2:5002
      --cluster.agency-endpoint tcp://arango-agent-3:5003
      --server.storage-engine rocksdb
    volumes:
      - ${DOCKER_VOLUME_MNT}/arango3/coord:/var/lib/arangodb3
      - ${DOCKER_VOLUME_MNT}/arango3/apps:/var/lib/arangodb3-apps
    depends_on:
      - arango-agent-1
      - arango-agent-2
      - arango-agent-3
    networks:
      - back
      - front
    ports:
      - 8003:8529
```

And a little script to create necessary folders 

```bash
#!/usr/bin/env bash

rm -rf $DOCKER_VOLUME_MNT/arango1
rm -rf $DOCKER_VOLUME_MNT/arango2
rm -rf $DOCKER_VOLUME_MNT/arango3

mkdir $DOCKER_VOLUME_MNT/arango1
mkdir $DOCKER_VOLUME_MNT/arango2
mkdir $DOCKER_VOLUME_MNT/arango3
mkdir $DOCKER_VOLUME_MNT/arango1/agent
mkdir $DOCKER_VOLUME_MNT/arango2/agent
mkdir $DOCKER_VOLUME_MNT/arango3/agent
mkdir $DOCKER_VOLUME_MNT/arango1/coord
mkdir $DOCKER_VOLUME_MNT/arango2/coord
mkdir $DOCKER_VOLUME_MNT/arango3/coord
mkdir $DOCKER_VOLUME_MNT/arango1/db
mkdir $DOCKER_VOLUME_MNT/arango2/db
mkdir $DOCKER_VOLUME_MNT/arango3/db
mkdir $DOCKER_VOLUME_MNT/arango1/apps
mkdir $DOCKER_VOLUME_MNT/arango2/apps
mkdir $DOCKER_VOLUME_MNT/arango3/apps

echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango1/db/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango2/db/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/agent/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/coord/ENGINE
echo $ARANGO_STORAGE_ENGINE > $DOCKER_VOLUME_MNT/arango3/db/ENGINE
```
