### ISSUE TITLE
Problem with ArangoDB version

### ISSUE THREAD

**Issue by sergionov** [arangodb/arangodb#3439]
## My environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [X] 3.2

Mode:
- [X] Cluster

Storage-Engine:
- [X] mmfiles

On this operating system:
- [ ] Linux 
  - [X] Ubuntu .deb

We were in 3.1.27 and decided to set up a cluster, so we upgraded to 3.2.3. After that, we set up the cluster and deployed it with Docker. The config is 3 coordinators and 2 db_servers. Yesterday, we upgraded to 3.2.4.

This is an example of coordinator configuration in docker-compose file:
```
coordinator1:
  image: arangodb/arangodb
  environment:
  - ARANGO_NO_AUTH=1
  command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://coordinator1:8529 --cluster.my-local-info coord1  --cluster.my-role COORDINATOR --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
  volumes:
  - ./data/c1:/var/lib/arangodb3
  - ./apps/c1:/var/lib/arangodb3-apps
  - ./logs/c1:/var/log/arangodb3
  ports: ['8629:8529']
  depends_on:
  - agency1
```

And this is an example of db server:
```
db1:
  image: arangodb/arangodb
  environment:
  - ARANGO_NO_AUTH=1
  command: arangod --server.authentication=false --server.endpoint tcp://0.0.0.0:8529 --cluster.my-address tcp://db1:8529 --cluster.my-local-info db1 --cluster.my-role PRIMARY --cluster.agency-endpoint tcp://agency1:8529 --log.file /var/log/arangodb3/arangod.log
  volumes:
  - ./data/d1:/var/lib/arangodb3
  - ./logs/d1:/var/log/arangodb3
  depends_on:
  - agency1
  - coordinator1
  - coordinator2
```

### this is a web interface-related issue:
I'm using the web interface with this browser:  Chrome   running on this OS: Ubuntu 16.04
- [X] authentication is enabled?
- [X] using the cluster?
- [X] _system database?

The following problem occurs: 
If I check the installed version of Arango in my server, the version is 3.2.4.

![captura de pantalla de 2017-10-17 10-42-03](https://user-images.githubusercontent.com/9535909/31655048-fc3dff84-b327-11e7-8dc3-9e3c2a895e14.png)

But web UI displays 3.2.3.

![captura de pantalla de 2017-10-17 10-42-27](https://user-images.githubusercontent.com/9535909/31655059-0152c144-b328-11e7-9e79-e7bfdaff87c0.png)

Instead I would be expecting: 
Web UI displays 3.2.4.
