### ISSUE TITLE
Hostname configuration is altered by arango

### ISSUE THREAD

**Issue by huepf** [arangodb/arangodb#5804]
## My Environment

* __ArangoDB Version__:       3.3.11
* __Deployment Mode__:       Active Failover
* __Configuration__:               see config below
* __Operating System__:        Ubuntu 18.04
* __Used Package__:              Ubuntu .deb

## Component, Query & Data

__Affected feature__:
Communication in a cluster is not working. Arango turns the hostname 'A1' to a lower case hostname 'a1'. This might be ok on a "normal" host but if we define a docker service as 'A1' it makes a difference as there is no service 'a1'.

## Steps to reproduce

1. save the stack config below in a stack.yml file.
```
version: "3.4"

services:
 A1:
   image: arangodb/arangodb:3.3.11
   command: "--server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://A1:5001 --agency.activate true --agency.size 3 --agency.endpoint tcp://A1:5001 --agency.supervision true --server.jwt-secret arangosecret"
   environment:
     - ARANGO_NO_AUTH=1
   volumes:
     - A1data:/var/lib/arangodb3
     - A1apps:/var/lib/arangodb3-apps
   ports:
     - 5001:5001
   networks:
     - arangonet
     
 A2:
   image: arangodb/arangodb:3.3.11
   command: "--server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://A2:5001 --agency.activate true --agency.size 3 --agency.endpoint tcp://A1:5001 --agency.supervision true --server.jwt-secret arangosecret"
   environment:
     - ARANGO_NO_AUTH=1
   volumes:
     - A2data:/var/lib/arangodb3
     - A2apps:/var/lib/arangodb3-apps
   ports:
     - 5002:5001
   networks:
     - arangonet
     
 A3:
   image: arangodb/arangodb:3.3.11
   command: "--server.endpoint tcp://0.0.0.0:5001 --agency.my-address tcp://A3:5001 --agency.activate true --agency.size 3 --agency.endpoint tcp://A1:5001 --agency.supervision true --server.jwt-secret arangosecret"
   environment:
     - ARANGO_NO_AUTH=1
   volumes:
     - A3data:/var/lib/arangodb3
     - A3apps:/var/lib/arangodb3-apps
   ports:
     - 5003:5001
   networks:
     - arangonet
     
 db1:
   image: arangodb/arangodb:3.3.11
   command: "--server.endpoint tcp://0.0.0.0:8529 --server.jwt-secret arangosecret --cluster.my-address tcp://db1:8529 --cluster.my-role SINGLE --cluster.agency-endpoint tcp://A1:5001 --cluster.agency-endpoint tcp://A2:5001 --cluster.agency-endpoint tcp://A3:5001 --replication.automatic-failover true"
   environment:
     - ARANGO_NO_AUTH=1
   volumes:
     - db1data:/var/lib/arangodb3
     - db1apps:/var/lib/arangodb3-apps
   ports:
     - 8529:8529
   networks:
     - arangonet
     
 db2:
   image: arangodb/arangodb:3.3.11
   command: "--server.endpoint tcp://0.0.0.0:8529 --server.jwt-secret arangosecret --cluster.my-address tcp://db2:8529 --cluster.my-role SINGLE --cluster.agency-endpoint tcp://A1:5001 --cluster.agency-endpoint tcp://A2:5001 --cluster.agency-endpoint tcp://A3:5001 --replication.automatic-failover true"
   environment:
     - ARANGO_NO_AUTH=1
   volumes:
     - db2data:/var/lib/arangodb3
     - db2apps:/var/lib/arangodb3-apps
   ports:
     - 8530:8529
   networks:
     - arangonet
     
volumes:
 db1data:
 db1apps:
 db2data:
 db2apps:
 A1data:
 A1apps:
 A2data:
 A2apps:
 A3data:
 A3apps:

networks:
 arangonet:
   attachable: true
```
2. deploy the stack with `docker stack deploy ./stack.yml arango`
3. wait until the services are running and have a look at the logs of the dbs: `docker service logs arango_db1` `docker service logs arango_db2`

__Problem__:
db1 and db2 try to connect to the agency hostname 'a1' instead of hostname 'A1'.
log output:
```
arango_db2.1.qbep0kbrp3eq@florian    | 2018-07-09T08:54:17Z [1] INFO {agencycomm} Flaky agency communication to http+tcp://a1:5001. Unsuccessful consecutive tries: 40 (48.74s). Network checks advised.
arango_db2.1.qbep0kbrp3eq@florian    | 2018-07-09T08:54:21Z [1] INFO {agencycomm} Flaky agency communication to http+tcp://a2:5001. Unsuccessful consecutive tries: 41 (52.64s). Network checks advised.
arango_db2.1.qbep0kbrp3eq@florian    | 2018-07-09T08:54:25Z [1] INFO {agencycomm} Flaky agency communication to http+tcp://a3:5001. Unsuccessful consecutive tries: 42 (56.82s). Network checks advised.
arango_db2.1.qbep0kbrp3eq@florian    | 2018-07-09T08:54:29Z [1] INFO {agencycomm} Flaky agency communication to http+tcp://a1:5001. Unsuccessful consecutive tries: 43 (61.33s). Network checks advised.
```

__Expected result__:
If I define a hostname in the config I expect the hostname to be as defined and not altered by arango. E.g. if I define a hostname with upper case I expect arango to use it in upper case and not turn it to lower case. As I said it might not make a difference for 'normal' hosts but inside docker things are slightly different.
