### ISSUE TITLE
Setting of `.v8-contexts` in Kubernetes Deployment Cluster does not work.

### ISSUE THREAD

**Issue by lanluu** [arangodb/arangodb#7316]
## My Environment

* __ArangoDB Version__:  3.4 RC4
* __Deployment Mode__:   Cluster
* __Infrastructure__: **Kubernetes**; GKE; 4 Nodes; 1 vCPUs; 1.75 GB each Node

## Issue
Setting of `.v8-contexts` does not work.

My deployment script/yaml:
```
args:
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
 name: "arangodb"
spec:
 mode: Cluster
 image: arangodb/arangodb-preview:v3.4.0-rc.4
 coordinators:
  count: 3
  args:
   - --javascript.v8-contexts=4
```
