### ISSUE TITLE
Jobs in Foxx Queue are always "pending" in both Cluster and Single Server

### ISSUE THREAD

**Issue by lanluu** [arangodb/arangodb#7317]
### Cluster
* __ArangoDB Version__:  3.4 RC4
* __Deployment Mode__:   Cluster
* __Infrastructure__: **Kubernetes**; GKE; 4 Nodes; 1 vCPUs; 1.75 GB each Node and **Kubernetes**; GKE; 2 Nodes; 2 vCPUs; 7.5 GB each Node

Deployment YAML: I tried once with ---javascript.v8-contexts=4 and once without. Same results!
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
 name: "arangodb"
spec:
 mode: Cluster
 image: arangodb/arangodb-preview:v3.4.0-rc.4
 coordinators:
  count: 3
  args:
   - --javascript.v8-contexts=4
```

### Single Server
* __ArangoDB Version__:  3.4 RC3 and 3.4 RC4
* __Deployment Mode__:   Single Server
* __Infrastructure__: both **Kubernetes**; GKE; 1 Node; 2 vCPUs; 7.5 GB  and *Windows 10*

Deployment YAML:
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
 name: "arangodb"
spec:
 mode: Single
 image: arangodb/arangodb-preview:v3.4.0-rc.4
```

## Issue
`Jobs` in `Foxx Queue` are always `pending` i.e they are not executed.
`Queue` has 1 Worker.
I already setup another stronger Cluster with more CPUs, but it did not help.
